apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6
  namespace: argocd
spec:
  project: default
  source:
    chart: k6-operator
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.4.0
    helm:
      releaseName: k6
  destination:
    server: "https://kubernetes.default.svc"
    namespace: k6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
