apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operator
  namespace: argocd
spec:
  project: default
  source:
    path: ./chart/opensearch-operator/
    #repoURL: "xfile://."
    targetRevision: 2.4.0
    helm:
      releaseName: opensearch-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
