apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argocd
spec:
  project: default
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.0.1
    helm:
      releaseName: lgtm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
