apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
          additionalDataSources:
            - name: tempo
              type: tempo
              url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
            - name: loki
              type: loki
              url: http://loki.loki.svc.cluster.local:3100  
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
                  storageClassName: "standard"
                  # storageClassName: "do-block-storage"
            additionalScrapeConfigs:
              - job_name: 'tempo'
                static_configs:
                  - targets: 
                    - 'tempo-compactor.tempo.svc.cluster.local:3100'
                    - 'tempo-distributor-discovery.tempo.svc.cluster.local:3100'    
                    - 'tempo-gossip-ring.tempo.svc.cluster.local:3100'      
                    - 'tempo-ingester.tempo.svc.cluster.local:3100'                  
                    - 'tempo-ingester-discovery.tempo.svc.cluster.local:3100'        
                    - 'tempo-querier.tempo.svc.cluster.local:3100'                   
                    - 'tempo-query-frontend.tempo.svc.cluster.local:3100'           
                    - 'tempo-query-frontend-discovery.tempo.svc.cluster.local:3100'
              - job_name: 'promtail'
                static_configs:
                  - targets: ['promtail-service.loki.svc.cluster.local:3101']
              - job_name: 'loki'
                static_configs:
                  - targets: ['loki.loki.svc.cluster.local:3100']
        namespaceOverride: kube-prometheus-stack
      releaseName: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
