apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /$2
            path: "/grafana(/|$)(.*)"
          additionalDataSources:
            - name: tempo
              type: tempo
              url: http://tempo.tempo.svc.cluster.local:3100
            - name: loki
              type: loki
              url: http://loki.loki.svc.cluster.local:3100  
        prometheus:
          ingress:
            enabled: true
              annotations:
                kubernetes.io/ingress.class: nginx
              paths: 
                - '/prometheus'
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: 'tempo'
                static_configs:
                  - targets: ['tempo.tempo.svc.cluster.local:3100']
              - job_name: 'promtail'
                static_configs:
                  - targets: ['promtail-service.loki.svc.cluster.local:3101']
              - job_name: 'loki'
                static_configs:
                  - targets: ['loki.loki.svc.cluster.local:3100']
        namespaceOverride: kube-prometheus-stack
      releaseName: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
