apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.41.4
    helm:
      valuesObject:
        loki:
          auth_enabled: false
          minio:
            enabled: true
      releaseName: loki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
