apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.4
    helm:
      valuesObject:
        loki:
          storage:
            type: s3
            bucketNames:
              chunks: "chunks"
              ruler: "ruler"
              admin: "admin"
            s3:
              endpoint: 'minio.minio.svc.cluster.local:9000'
              s3ForcePathStyle: true
              accessKeyId: 'admin'
              secretAccessKey: 'supersecret'
              insecure: true
          auth_enabled: false
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
            max_concurrent: 4
        deploymentMode: SimpleScalable
        backend:
          replicas: 3
        read:
          replicas: 3
        write:
          replicas: 3
        # Enable minio for storage
        minio:
          enabled: false
        # Zero out replica counts of other deployment modes
        singleBinary:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
      releaseName: loki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
