apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.min.io/
    targetRevision: 5.0.15
    helm:
      valuesObject:
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 4Gi
        replicas: 4
        buckets:
          - name: tempo-traces
            policy: tempo-traces
            purge: false
        persistence:
          size: 25Gi
        rootUser: "admin"
        rootPassword: "admin"
      releaseName: minio
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
