apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.4
    helm:
      valuesObject:
        traces:
          otlp:
            grpc:
              enabled: true
      releaseName: tempo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
