apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.4
    helm: 
      valuesObject:
        backend:                                          
          s3:
            bucket: tempo                                   
            endpoint: minio-s3.minio.svc.cluster.local  
            accessKey: minio                            
            secretKey: minio123                          
            insecure: true                                 
        storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
        minio:
          enabled: true
          defaultBucket:
            enabled: true
            name: tempo
          accessKey: minio
          secretKey: minio123
          persistence:
            enabled: true
            size: 50Gi
        ingester:
          replicas: 3
          persistence:
            enabled: false
        traces:
          otlp:
            grpc:
              enabled: true
      releaseName: tempo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tempo
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: tempo
#     repoURL: https://grafana.github.io/helm-charts
#     targetRevision: 1.7.1
#     helm:
#       valuesObject:
#         persistence:
#           enabled: true
#           accessModes:
#             - ReadWriteOnce
#           size: 50Gi
#
#       releaseName: tempo
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: tempo
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
