apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  source:
    chart: fluent-bit
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.40.0
    helm:
      valuesObject:
        backend:
          type: es
          es:
            host: opensearch.my-cluster.svc.cluster.local
            port: 9200
            index: 'kubernetes_cluster'
        metrics:
          enabled: true
          namespace: fluentbit
          interval: 30s
          scrapeTimeout: 10s 
        dashboards:
          enabled: true
      releaseName: fluentbit
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fluentbit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
