apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  source:
    chart: fluent-bit
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.40.0
    helm:
      valuesObject:
        logLevel: debug
        service:
          logLevel: debug
        config:
          outputs: |
           [OUTPUT]
               Name opensearch
               Match *
               Host opensearch-cluster-master.opensearch.svc.cluster.local
               Port 9200
               #Logstash_Format On
               #Logstash_Prefix infra
               Retry_Limit False
               HTTP_User admin
               HTTP_Passwd admin
               tls On
               tls.verify Off
               #Include_Tag_Key On
               #Trace_Error On
               Write_Operation create
               Suppress_Type_Name On
               #Replace_Dots On
        metrics:
          enabled: true
          namespace: fluentbit
          interval: 30s
          scrapeTimeout: 10s 
        dashboards:
          enabled: true
      releaseName: fluentbit
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
