# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: fluentbit
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: fluent-bit
#     repoURL: https://fluent.github.io/helm-charts
#     targetRevision: 0.40.0
#     helm:
#       valuesObject:
#         daemonset:
#           enabled: true
#         logLevel: debug
#         config:
#           service: |
#             [SERVICE]
#                 Daemon Off
#                 Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf
#                 Config_Watch On
#                 HTTP_Server On
#                 HTTP_Listen 0.0.0.0
#           inputs: |
#             [INPUT]
#                 Name              tail
#                 Tag               kube.*
#                 Path              /var/log/containers/*.log
#                 multiline.parser  docker
#                 Mem_Buf_Limit     5MB
#                 Skip_Long_Lines   On
#                 Refresh_Interval  5
#           filters: |
#             [FILTER]
#                 Name                kubernetes
#                 Match               kube.*
#                 Kube_URL            https://kubernetes.default.svc:443
#                 Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#                 Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
#                 Merge_Log           On
#                 K8S-Logging.Parser  On
#                 K8S-Logging.Exclude Off
#           outputs: |
#            [OUTPUT]
#                Name opensearch
#                Match *
#                Host opensearch-cluster-master.opensearch.svc.cluster.local
#                Port 9200
#                Logstash_Format On
#                #Logstash_Prefix infra
#                Retry_Limit False
#                HTTP_User admin
#                HTTP_Passwd admin
#                Type _doc
#                tls On
#                tls.verify Off
#                #Include_Tag_Key On
#                #Trace_Error On
#                Write_Operation create
#                Suppress_Type_Name On
#                Replace_Dots On
#         metrics:
#           enabled: true
#           namespace: fluentbit
#           interval: 30s
#           scrapeTimeout: 10s 
#         dashboards:
#           enabled: true
#       releaseName: fluentbit
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: opensearch
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
