apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: 'loki'
                static_configs:
                  - targets: 
                    #- fluentbit-fluent-bit.fluentbit.svc.cluster.local:2020/api/v1/metrics/prometheus
                      #- opesnearch
                    - argocd-applicationset-controller.argocd.svc.cluster.local:8080/metrics
                    - jaeger-query.jaeger.svc.cluster.local:16687/metrics  
                    - jaeger-agent.jaeger.svc.cluster.local:14271/metrics  
                    - jaeger-collector.jaeger.svc.cluster.local:14269/metrics  
        namespaceOverride: kube-prometheus-stack
      releaseName: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
