apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: opensearch
                scrape_interval: 10s
                scheme: https
                basic_auth:
                  username: 'admin'
                  password: 'admin'
                tls_config:
                  insecure_skip_verify: true
                metrics_path: "/_prometheus/metrics"
                static_configs:
                  - targets:
                    - opensearch-cluster-master.opensearch.svc.cluster.local:9200
              - job_name: 'fluentbit'
                metrics_path: /api/v1/metrics/prometheus
                static_configs:
                  - targets:
                    - fluentbit-fluent-bit.fluentbit.svc.cluster.local:2020
              - job_name: 'jaeger'
                static_configs:
                  - targets:
                    - jaeger-query.jaeger.svc.cluster.local:16687 
                    - jaeger-agent.jaeger.svc.cluster.local:14271
                    - jaeger-collector.jaeger.svc.cluster.local:14269
              - job_name: 'argo'
                static_configs:
                  - targets: 
                    - argocd-applicationset-controller.argocd.svc.cluster.local:8080
        namespaceOverride: kube-prometheus-stack
      releaseName: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
