apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    chart: opensearch
    repoURL: https://opensearch-project.github.io/helm-charts
    targetRevision: 2.17.2
    helm:
      valuesObject:
        persistence:
            size: 200Gi
        config: 
          opensearch.yml: |
            logger.org.opensearch.index.reindex: debug
            cluster.name: opensearch-cluster
            network.host: 0.0.0.0
            plugins:
              security:
                ssl:
                  transport:
                    pemcert_filepath: esnode.pem
                    pemkey_filepath: esnode-key.pem
                    pemtrustedcas_filepath: root-ca.pem
                    enforce_hostname_verification: false
                  http:
                    enabled: true
                    pemcert_filepath: esnode.pem
                    pemkey_filepath: esnode-key.pem
                    pemtrustedcas_filepath: root-ca.pem
                allow_unsafe_democertificates: true
                allow_default_init_securityindex: true
                authcz:
                  admin_dn:
                    - CN=kirk,OU=client,O=client,L=test,C=de
                audit.type: internal_opensearch
                enable_snapshot_restore_privilege: true
                check_snapshot_restore_write_privileges: true
                restapi:
                  roles_enabled: ["all_access", "security_rest_api_access"]
                system_indices:
                  enabled: true
                  indices:
                    [
                      ".opendistro-alerting-config",
                      ".opendistro-alerting-alert*",
                      ".opendistro-anomaly-results*",
                      ".opendistro-anomaly-detector*",
                      ".opendistro-anomaly-checkpoints",
                      ".opendistro-anomaly-detection-state",
                      ".opendistro-reports-*",
                      ".opendistro-notifications-*",
                      ".opendistro-notebooks",
                      ".opendistro-asynchronous-search-response*",
                    ]
              query:
                datasources:
                  encryption:
                    masterkey: e5uoVxE/XSEoAI4GiU986DMQdNjN1RHd   
        plugins:
          enabled: true
          installList:
            - 'https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.11.1.0/prometheus-exporter-2.11.1.0.zip'
      releaseName: opensearch
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
