apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    chart: opensearch
    repoURL: https://opensearch-project.github.io/helm-charts
    targetRevision: 2.17.2
    helm:
      valuesObject:
        replicas: 1
        opensearch.yml: |
          compatibility:
            override_main_response_version: true
      releaseName: opensearch
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
