apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.80.1
    helm:
      valuesObject:
        mode: deployment
        config:
          receivers:
            otlp:
              protocols:
                grpc:
          exporters:
            otlp/jaeger:
              endpoint: jaeger-collector.jaeger.svc.cluster.local:14250
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [otlp]
                exporters: [otlp/jaeger]
      releaseName: otel-collector
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jaeger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
