apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: loki
spec:
  type: ClusterIP 
  ports:
    - port: 3101
      targetPort: 3101
      protocol: TCP
  selector:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
