apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-server
  namespace: ffmpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg-server
  template:
    metadata:
      labels:
        app: ffmpeg-server
    spec:
      containers:
      - name: ffmpeg-server
        image: dap5/ffmpeg-server:v0.2
        command: ["/go-ffmpeg"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg-server-service
  namespace: ffmpeg
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ffmpeg-server